language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - vue-cli-service build

after_script:

branches:
  only:
    - master
